### ISSUE TITLE
Use of external crate "log" vs current module "log"?

### ISSUE THREAD

**Issue by RuijieYu** [anBertoli/ariadne-dns#8]
I am looking at the file `src/common/log.rs` and noticed that it is largely similar in the calling semantics to the crate [`log`](https://crates.io/crates/log), such as `log::error!()`, etc.  I'm genuinely curious, is there a particular reason that you decided to write the logging functionality?

**Comment by anBertoli** [comment]
@RuijieYu I discovered later the crate [`log`](https://crates.io/crates/log) crate and its related implementations. I'm planning to replace the current log functionality with the more used crate [`log`](https://crates.io/crates/log) crate.  Thanks for pointing out! If you want to contribute feel free to open a PR.

**Comment by RuijieYu** [comment]
Thanks for your response! I have drafted some changes and will file a PR momentarily.

Also, I noticed that `cargo clippy` shows a lot of warnings, and I had to allow a lot of lints to fully silent the warnings.  To limit the scope, my PR has not touched anything regarding these lints.

**Comment by anBertoli** [comment]
Ehy, thanks for the PR! 😄 
Just give me some time and I will review it.
